[project]
name = "mini_proyecto"
version = "1.0.0"
description = "Mini proyecto: Cajero ElectrÃ³nico en Python"
authors = [{ name="Mateo", email="tu_correo@example.com"}]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
